/*
 * DELAY.c
 *
 *  Created on: Jul 17, 2024
 *      Author: Anas Dorgham
 */

#include "../../LIB/STD_TYPES.h"
#include "../../LIB/BIT_MATH.h"
#include "../../MCAL/DIO/DIO.h"
#include "../../MCAL/TIMER/TIMER.h"
#include "DELAY.h"
#define F_CPU		16000000UL

/* Variables */
u8_t delay_state;
u8_t delay_remaining_ms = 0;


/********************************\
*********** Functions ************
\********************************/

void DELAY_Timer0_us(u32_t time_in_us){
	if (time_in_us <= 16){
		TIMER_Timer0_Init(TIMER0_CTC, TIMER0_NO_PRESCALER);
		TIMER_Timer0_OCR0_Set((u8_t) (time_in_us * (F_CPU / 1000000)) - 1);
	}
	else if (time_in_us <= 128){
		TIMER_Timer0_Init(TIMER0_CTC, TIMER0_PRESCALER_8);
		TIMER_Timer0_OCR0_Set((u8_t) (time_in_us * (F_CPU / 1000000) / 8) - 1);
	}
	else if (time_in_us <= 1024){
		TIMER_Timer0_Init(TIMER0_CTC, TIMER0_PRESCALER_64);
		TIMER_Timer0_OCR0_Set((u8_t) (time_in_us * (F_CPU / 1000000) / 64) - 1);
	}
	else{					// If the requested delay is more than 1024us.
		// Divide it into two delays, one in ms and the other in us.
		u32_t ms_part = (u32_t) (time_in_us / 1000);		// Divide the delay by 1000 to get the ms part.
		DELAY_Timer0_ms(ms_part);
		time_in_us%= 1000;									// The us part is the fraction of the delay divided by 1000.
		DELAY_Timer0_us(time_in_us);
	}
	TIMER_Timer0_OC_Polling_Wait();
}

void DELAY_Timer0_ms(float time_in_ms){
	if (time_in_ms - (int) time_in_ms > 0){
		DELAY_Timer0_us((time_in_ms - (int) time_in_ms) * 1000);
		time_in_ms = (int) time_in_ms;
	}

    while (time_in_ms > 0) {
        if (time_in_ms == 1) {
            TIMER_Timer0_OCR0_Set(249);
            TIMER_Timer0_Init(TIMER0_CTC, TIMER0_PRESCALER_64);
            time_in_ms = 0;
        } else if (time_in_ms <= 4) {
            TIMER_Timer0_OCR0_Set((u8_t)((time_in_ms * (F_CPU / 1000) / 256) - 1));
            TIMER_Timer0_Init(TIMER0_CTC, TIMER0_PRESCALER_256);
            time_in_ms = 0;
        } else if (time_in_ms <= 16) {
            TIMER_Timer0_OCR0_Set((u8_t)((time_in_ms * (F_CPU / 1000) / 1024) - 1));
            TIMER_Timer0_Init(TIMER0_CTC, TIMER0_PRESCALER_1024);
            time_in_ms = 0;
        } else {  // For longer delays, split into 16ms chunks
            TIMER_Timer0_OCR0_Set((u8_t)((16 * (F_CPU / 1000) / 1024) - 1));
            TIMER_Timer0_Init(TIMER0_CTC, TIMER0_PRESCALER_1024);
            time_in_ms -= 16;
        }
        TIMER_Timer0_OC_Polling_Wait();
    }
}

void DELAY_Timer0_s(float time_in_s){
	// The maximum delay to be generated by Timer0 is 16.384ms, so we call the DELAY_Timer0_ms function with time in seconds converted to be in milliseconds.
	DELAY_Timer0_ms(time_in_s * 1000);
}



void DELAY_Timer1_us(u32_t time_in_us){
	while (time_in_us > 0) {
		if (time_in_us <= 4096){
			TIMER_Timer1_OCR1A_Set((u16_t) (time_in_us * (F_CPU / 1000000)) - 1);
			TIMER_Timer1_Init(TIMER1_CTC_OCR1, TIMER1_NO_PRESCALER);
			time_in_us = 0;
		}
		else if (time_in_us <= 32768){
			TIMER_Timer1_OCR1A_Set((u16_t) (time_in_us * (F_CPU / 1000000) / 8) - 1);
			TIMER_Timer1_Init(TIMER1_CTC_OCR1, TIMER1_PRESCALER_8);
			time_in_us = 0;
		}
		else if (time_in_us <= 262144){
			TIMER_Timer1_OCR1A_Set((u16_t) (time_in_us * (F_CPU / 1000000) / 64) - 1);
			TIMER_Timer1_Init(TIMER1_CTC_OCR1, TIMER1_PRESCALER_64);
			time_in_us = 0;
		}
		else if (time_in_us <= 1048576){
			TIMER_Timer1_OCR1A_Set((u16_t) (time_in_us * (F_CPU / 1000000) / 256) - 1);
			TIMER_Timer1_Init(TIMER1_CTC_OCR1, TIMER1_PRESCALER_256);
			time_in_us = 0;
		}
		else if (time_in_us <= 4194304){
			TIMER_Timer1_OCR1A_Set((u16_t) (time_in_us * (F_CPU / 1000000) / 1024) - 1);
			TIMER_Timer1_Init(TIMER1_CTC_OCR1, TIMER1_PRESCALER_1024);
			time_in_us = 0;
		}
		else{
			// For longer delays, split into 4194304us chunks
			TIMER_Timer1_OCR1A_Set((u16_t) (4194304 * (F_CPU / 1000000) / 1024) - 1);
			TIMER_Timer1_Init(TIMER1_CTC_OCR1, TIMER1_PRESCALER_1024);
			time_in_us -= 4194304;
		}
		TIMER_Timer1_OCA_Polling_Wait();
	}
}

void DELAY_Timer1_ms(float time_in_ms){
    DELAY_Timer1_us(time_in_ms * 1000);
}

void DELAY_Timer1_s(float time_in_s){
	DELAY_Timer1_us(time_in_s * 1000000);
}


void DELAY_Timer2_us(u32_t time_in_us){
	if (time_in_us <= 16){
		TIMER_Timer2_Init(TIMER2_CTC, TIMER2_NO_PRESCALER);
		TIMER_Timer2_OCR2_Set((u8_t) (time_in_us * (F_CPU / 1000000)) - 1);
	}
	else if (time_in_us <= 128){
		TIMER_Timer2_Init(TIMER2_CTC, TIMER2_PRESCALER_8);
		TIMER_Timer2_OCR2_Set((u8_t) (time_in_us * (F_CPU / 1000000) / 8) - 1);
	}
	else if (time_in_us <= 512){
		TIMER_Timer2_Init(TIMER2_CTC, TIMER2_PRESCALER_32);
		TIMER_Timer2_OCR2_Set((u8_t) (time_in_us * (F_CPU / 1000000) / 32) - 1);
	}
	else if (time_in_us <= 1024){
		TIMER_Timer2_Init(TIMER2_CTC, TIMER2_PRESCALER_64);
		TIMER_Timer2_OCR2_Set((u8_t) (time_in_us * (F_CPU / 1000000) / 64) - 1);
	}
	else{					// If the requested delay is more than 1024us.
		// Divide it into two delays, one in ms and the other in us.
		u32_t ms_part = (u32_t) (time_in_us / 1000);		// Divide the delay by 1000 to get the ms part.
		DELAY_Timer2_ms(ms_part);
		time_in_us%= 1000;									// The us part is the fraction of the delay divided by 1000.
		DELAY_Timer2_us(time_in_us);
	}
	TIMER_Timer2_OC_Polling_Wait();
}

void DELAY_Timer2_ms(float time_in_ms){
	if (time_in_ms - (int) time_in_ms > 0){
		DELAY_Timer2_us((time_in_ms - (int) time_in_ms) * 1000);
		time_in_ms = (int) time_in_ms;
	}

    while (time_in_ms > 0) {
        if (time_in_ms == 1) {
            TIMER_Timer2_OCR2_Set(249);
            TIMER_Timer2_Init(TIMER2_CTC, TIMER2_PRESCALER_64);
            time_in_ms = 0;
        }
        if (time_in_ms <= 2) {
        	TIMER_Timer2_OCR2_Set((u8_t)((time_in_ms * (F_CPU / 1000) / 128) - 1));
        	TIMER_Timer2_Init(TIMER2_CTC, TIMER2_PRESCALER_128);
        	time_in_ms = 0;
        }
        else if (time_in_ms <= 4) {
            TIMER_Timer2_OCR2_Set((u8_t)((time_in_ms * (F_CPU / 1000) / 256) - 1));
            TIMER_Timer2_Init(TIMER2_CTC, TIMER2_PRESCALER_256);
            time_in_ms = 0;
        } else if (time_in_ms <= 16) {
            TIMER_Timer2_OCR2_Set((u8_t)((time_in_ms * (F_CPU / 1000) / 1024) - 1));
            TIMER_Timer2_Init(TIMER2_CTC, TIMER2_PRESCALER_1024);
            time_in_ms = 0;
        } else {  // For longer delays, split into 16ms chunks
            TIMER_Timer2_OCR2_Set((u8_t)((16 * (F_CPU / 1000) / 1024) - 1));
            TIMER_Timer2_Init(TIMER2_CTC, TIMER2_PRESCALER_1024);
            time_in_ms -= 16;
        }
        TIMER_Timer2_OC_Polling_Wait();
    }
}

void DELAY_Timer2_s(float time_in_s){
	// The maximum delay to be generated by Timer2 is 16.384ms, so we call the DELAY_Timer2_ms function with time in seconds converted to be in milliseconds.
	DELAY_Timer2_ms(time_in_s * 1000);
}
